language: r
sudo: false
cache: packages

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"
    - secure: IW4WkUu0aFXffVnTULLOlYJuD1EdzoC1wEyJMN2SY0cz8AFBHuqcCqqxixhZ0yLlRNK3cDe9lGkksRjqrjusE345oDePAxP1y+g2xozCVoh/jaoMJqxupftVRNuaA+ODc1OZ/ZZUI2DSVRCCMre1nb1uI4A1fBA1R2lCdaOPMBc=

repos:
  XRAN: https://yihui.name/xran

before_install:
  - "curl -L https://yihui.name/xran/.gitconfig -o ~/.gitconfig"

after_success:
  - "(curl -L https://yihui.name/xran/r-xran | bash)"
